"""site info table

Revision ID: 337bb23788f5
Revises: 3f7d48bb9e93
Create Date: 2018-03-31 15:48:17.581120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337bb23788f5'
down_revision = '3f7d48bb9e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_info',
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=True),
    sa.Column('bio', sa.UnicodeText(), nullable=True),
    sa.Column('events', sa.UnicodeText(), nullable=True),
    sa.Column('issues', sa.UnicodeText(), nullable=True),
    sa.Column('volunteer_url', sa.UnicodeText(), nullable=True),
    sa.Column('donate_url', sa.UnicodeText(), nullable=True),
    sa.Column('legal', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.PrimaryKeyConstraint('site_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_info')
    # ### end Alembic commands ###
