"""site info table

Revision ID: 429a3b4d2b6c
Revises: f61e52976d0b
Create Date: 2018-03-24 14:55:49.295294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '429a3b4d2b6c'
down_revision = 'f61e52976d0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_info',
    sa.Column('site_id', sa.String(length=32), nullable=False),
    sa.Column('campaign_id', sa.String(length=32), nullable=True),
    sa.Column('name', sa.UnicodeText(), nullable=True),
    sa.Column('bio', sa.UnicodeText(), nullable=True),
    sa.Column('events', sa.UnicodeText(), nullable=True),
    sa.Column('issues', sa.UnicodeText(), nullable=True),
    sa.Column('donations_url', sa.UnicodeText(), nullable=True),
    sa.Column('volunteer_url', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.campaign_id'], ),
    sa.PrimaryKeyConstraint('site_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_info')
    # ### end Alembic commands ###
