"""add name columns to Candidate table

Revision ID: f61e52976d0b
Revises: 1162c4d7ad04
Create Date: 2018-03-08 07:42:25.947924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f61e52976d0b'
down_revision = '1162c4d7ad04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('first_name', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('last_name', sa.String(length=64), nullable=True))
    op.add_column('candidate', sa.Column('middle_name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_candidate_last_name'), 'candidate', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_last_name'), table_name='candidate')
    op.drop_column('candidate', 'middle_name')
    op.drop_column('candidate', 'last_name')
    op.drop_column('candidate', 'first_name')
    # ### end Alembic commands ###
